;;; start from (1, 1)
(define (f row col)
  (cond ((> col row) 0)
        ((< col 0) 0)
        ((= 1 col) 1)
        ((= col row) 1)
        (else (+ (f (- row 1) (- col 1))
                 (f (- row 1) col)
              )
        )
  )
)

(f 1 1)
(f 2 2)
(f 3 2)
(f 4 2)
(f 5 2)
(f 5 3) 
