(define (even? n)
  (= (remainder n 2) 0)
)

(define (integral f a b n)
  (define (coefficient cur)
    (cond ((= cur 0) 1)
          ((= cur n) 1)
          ((even? cur) 2)
          (else 4)
    )
  )
  (define (h) (/ (- b a) n))
  (define (y cur)
    (f (+ a (* cur (h))))
  )
  (define (iter-sum cur total)
    (cond ((> cur n) total)
          (else (iter-sum (+ 1 cur) (+ total (* (coefficient cur) (y cur)))))
    )
  )
  (* (/ (h) 3) (iter-sum 0 0))
)

(define (cube x)
  (* x x x)
)

(integral cube 0 1 100)
(integral cube 0 1 1000)
